import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <Link href="/" passHref>Home </Link> &nbsp;&nbsp;
          <Link href="/events" passHref>Events</Link>&nbsp;&nbsp;
          <Link href="/about-us" passHref>About us</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map(ev => 
          <Link key={ev.id} href={`/events/${ev.id}`} passHref>
            <Image width={200} height={200} src={ev.image} alt={ev.title} /> <h2>{ev.title}</h2> <p>{ev.description}</p>
          </Link>
        )}
      </main>

      <footer className={styles.footer}>
        <p>WE SPEAK YOUR LANGUAGE</p>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  //async function por que tenemos que esperar a la respuesta
  const { events_categories } = await import("/data/data.json"); //usamos await con import por ser funcion asincrona ya que devuelve una promise
  return {
    props: {
      data: events_categories,
    },
  };
}
